---
- hosts: all
  strategy: free
  tasks:
    # Run Packer
    - name: Running packer build
      become: true
      command: >
          packer build \
            -timestamp-ui \
            -only={{ builders }} \
            -except={{ skip_post_processors }} \
            -var-file="{{ build_path }}/{{ build_version }}/{{ build_type }}/{{ box_info_path }}" \
            -var-file="{{ build_path }}/{{ build_version }}/{{ build_type }}/{{ template_path }}" \
            "{{ build_path }}/{{ build_os|lower }}-{{ build_type }}".json
      environment:
        TMPDIR: /virtual_machines/tmp/
      args:
        chdir: "{{ build_path }}/{{ build_version }}/{{ build_type }}"
      when: ansible_os_family == "Debian"
      register: packer_run
      retries: 3
      delay: 10
