# action.yml
name: 'Run Ansible'
description: 'Runs Ansible'
inputs:
  playbook:  # id of input
    description: 'ansible playbook to run'
    required: true
    default: 'destroy.yml'
outputs:
  starttime:
    description: 'The time ansible-playbook started.'
  endtime:
    description: 'The time ansible-playbook finished.'
runs:
  using: 'docker'
  image: 'docker://bunchc/ironic-factory'
  args:
    - ${{ inputs.playbook }}
    - ${{ inputs.inventory }}
