# action.yml
name: 'Run Ansible'
description: 'Runs Ansible'
inputs:
  playbook:  # Which ansible playbook to run
    description: 'Ansible playbook to run'
    required: true
    default: '/ansible/destroy.yml'
  inventory: # Path to ansible inventory file
    description: 'Ansible inventory file'
    required: false
outputs:
  starttime:
    description: 'The time ansible-playbook started.'
  endtime:
    description: 'The time ansible-playbook finished.'
runs:
  using: 'docker'
  image: 'docker://bunchc/ironic-factory'
  args:
    - ${{ inputs.playbook }}
    - ${{ inputs.inventory }}
