---
- name:
    Delete a Rackspace cloud server.
  hosts: localhost
  connection: local
  vars:
    destroy_host: false
    debug_workflow: false
    pip_pyrax: false
  tasks:
    - name: "Include debugging"
      include_tasks: debug.yml
      when:
        - debug_workflow is defined
        - debug_workflow

    - name: Install Rackspace module dependencies
      pip:
        name: pyrax
        extra_args: --user --no-cache-dir
      when:
        - pip_pyrax is defined
        - pip_pyrax

    - name: Read inventory file
      include_vars:
        file: "{{ lookup('env', 'GITHUB_WORKSPACE') }}/inventory"
        name: imported_vars
    
    - name: Print server ID
      debug:
        msg: "Rackspace ID {{ item }}"
      with_items: "{{ imported_vars | json_query('all.hosts.*.rackspace_device_id') }}"

    - name: Delete the servers
      local_action:
        module: rax
        api_key: "{{ lookup('env', 'RACKSPACE_API_TOKEN') }}"
        username: "{{ lookup('env', 'RACKSPACE_USERNAME') }}"
        region: "{{ lookup('env', 'RACKSPACE_REGION') }}"
        instance_ids: "{{ item }}"
        state: absent
        wait: yes
        wait_timeout: 600
      register: rackspace_del
      retries: 5
      delay: 10
      until: rackspace_del is succeeded
      with_items: "{{ imported_vars | json_query('all.hosts.*.rackspace_device_id') }}"
      when:
        - destroy_host is defined
        - destroy_host